module.exports = {
  rules: {
      'body-leading-blank': [2, 'always'],
      'footer-leading-blank': [2, 'always'],
      'header-max-length': [2, 'always', 72],
      'scope-case': [2, 'always', 'lower-case'],
      'subject-case': [2, 'never', ['sentence-case', 'start-case', 'pascal-case', 'upper-case']],
      'subject-empty': [2, 'never'],
      'subject-exclamation-mark': [2, 'never'],
      'subject-full-stop': [2, 'never', '.'],
      'type-case': [2, 'always', 'lower-case'],
      'type-empty': [2, 'never'],
      'type-enum': [
          2,
          'always',
          [
            "🎉 init",
            "🔖 tag",
            "✨ feat",
            "🐛 bug",
            "💥 breaking",
            "🚑 critical",
            "🩹 fix",
            "🚧 wip",
            "📝 comment",
            "🛂 permissions",
            "🛂 roles",
            "🔒 security",
            "🔐 secrets",
            "💄 design",
            "💄 style",
            "🎨 animations",
            "🎨 transitions",
            "💎 improve",
            "🐎 perf",
            "♻️ refactor",
            "♿ accessability",
            "💻 desktop",
            "📱 mobile",
            "📱💻 responsive",
            "🏁 windows",
            "🍎 macOS",
            "🐧 linux",
            "🧪 test",
            "➕ addingtest",
            "📦 build",
            "🚀 deploy",
            "👷 ci",
            "👷 updateci",
            "📜 devscripts",
            "📚 docs",
            "📚 documentation",
            "🌐 internationalize",
            "🌐 i18n",
            "🌐 localisation",
            "📊 metadata",
            "👕 lint",
            "🩺 healtcheck",
            "👔 business",
            "🏗️ architectural",
            "🧑‍💻 developer",
            "⚡ generalupdate",
            "⬆️ upgrade",
            "⬇️ downgrade",
            "➕ add",
            "🔥 remove",
            "🚚 move",
            "🚚 rename",
            "➕ adddep",
            "➖removedep",
            "📌pindep",
            "👥 contributor",
            "🐳 docker",
            "🔧 config-file",
            "📦 pkg-file",
            "📈 analytics",
            "👽 api",
            "📄 licence",
            "🍱 assets",
            "✏️ gitfile",
            "📸 snapshots",
            "⚗️ experiments",
            "🔍️ seo",
            "🗃️ database",
            "🔊 update-logs",
            "🔇 remove-logs",
            "🔀 merge-branch",
            "⚰️ dead-code",
            "🗑️ bad-code",
            "⏪ revert",
            "👌 ok-code"
          ],
      ],
  },
};
