---
name: Pipeline - Auto Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Auto Sync
    runs-on: ubuntu-latest
    steps:
      # More info: https://github.com/peter-murray/workflow-application-token-action.
      - name: Get token
        id: get_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.ID_AUTOSYNCHROBOT }}
          application_private_key: ${{ secrets.PEM_AUTOSYNCHROBOT }}

      # More info: https://github.com/actions/checkout.
      - name: Checkout & Authentication
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          token: ${{ steps.get_token.outputs.token }}
          persist-credentials: false

      # More info: https://github.com/rovast/sync-upstream-repo/.
      - name: GitHub Sync to Upstream Repository
        uses: rovast/sync-upstream-repo@c90f27f86cd67d3f83899cd52311a3d739efb235
        with:
          upstream_repo: https://github.com/1Password/1password-teams-open-source
          token: ${{ steps.get_token.outputs.token }}
