name: Pipeline - PNPM Publish

on:
  push:
    branches:
      - main

jobs:
  npm-punlish:
    name: PNPM Publish
    runs-on: ubuntu-latest 
    steps:

    # More info: https://github.com/step-security/harden-runner.
      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0
        with:
          egress-policy: audit


      # More info: https://github.com/actions/checkout.
      - name: Checkout & Authentication
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Publish if version has been updated
        uses: wtrocki/npm-publish-action-monorepo@2.0.0
        with:
          workspace: "./packages"
          tag_name: "v%s"
          tag_message: "v%s"
          create_tag: "true"
          commit_pattern: "🔖 tag(create): Release (\\S+)"
          publish_args: "--non-interactive --dry-run"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
