name: Pipeline - PNPM Publish

on:
  push:
    branches:
      - main

jobs:
  npm-punlish:
    name: PNPM Publish
    runs-on: ubuntu-latest 
    steps:

    # More info: https://github.com/step-security/harden-runner.
      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          egress-policy: audit


      # More info: https://github.com/actions/checkout.
      - name: Checkout & Authentication
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Publish if version has been updated
        uses: wtrocki/npm-publish-action-monorepo@2.0.0
        with:
          workspace: "./packages"
          tag_name: "v%s"
          tag_message: "v%s"
          create_tag: "true"
          commit_pattern: "🔖 tag(create): Release (\\S+)"
          publish_args: "--non-interactive --dry-run"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
